[environments]
  [environments.development]
    name = "go"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = true
    override-ports = ["8888:80"]
    dockerfile = "Dockerfile"
    chart = "charts/go"
